drop table if exists government_idx cascade;
drop table if exists "containment and closure policies" cascade;
drop table if exists "economic policies" cascade;
drop table if exists "health system policies" cascade;
drop table if exists "vaccination policies" cascade;
drop table if exists vaccinated cascade;
drop table if exists confirmed cascade;
drop table if exists country_date cascade;
drop table if exists countries cascade;
drop table if exists continents cascade;
